name: Bug Report
description: Report a bug or issue with Magic-Link
title: '[Bug]: '
labels: ['bug', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to report a bug!
        
        Please fill out the information below to help us reproduce and fix the issue.
        
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug you're experiencing...
    validations:
      required: true
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
      
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true
      
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Configure magic link settings...
        2. Request magic link...
        3. Click on link...
        4. See error...
    validations:
      required: true
      
  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      description: Which feature is affected?
      options:
        - Magic Link Authentication
        - Email OTP (Premium)
        - TOTP / MFA (Advanced)
        - WhatsApp Integration
        - Token Management
        - IP Banning
        - Rate Limiting
        - JWT Sessions
        - Email Configuration
        - Admin UI
        - License System
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: auth-mode
    attributes:
      label: Authentication Mode
      description: Which authentication mode are you using?
      options:
        - Magic Link Only
        - Magic Link + Email OTP
        - Magic Link + TOTP
        - TOTP-Only Login
        - WhatsApp Magic Link
    validations:
      required: false
      
  - type: input
    id: plugin-version
    attributes:
      label: Plugin Version
      placeholder: e.g. 5.2.7
    validations:
      required: true
      
  - type: input
    id: strapi-version
    attributes:
      label: Strapi Version
      placeholder: e.g. 5.30.1
    validations:
      required: true
      
  - type: input
    id: node-version
    attributes:
      label: Node Version
      placeholder: e.g. 20.19.4
    validations:
      required: true
      
  - type: textarea
    id: error-logs
    attributes:
      label: Error Logs
      description: Please paste any relevant error logs
      render: shell
    validations:
      required: false
      
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Your plugin configuration (remove sensitive data!)
      render: javascript
    validations:
      required: false
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar issues
          required: true
        - label: I have removed sensitive information (passwords, API keys, etc.)
          required: true
