name: Feature Request
description: Suggest a new feature or enhancement for Magic-Link
title: '[Feature]: '
labels: ['enhancement', 'needs-triage']
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for suggesting a feature!
        
        Please describe your idea in detail below.
        
  - type: dropdown
    id: feature-area
    attributes:
      label: Feature Area
      options:
        - Magic Link Authentication
        - Email OTP
        - TOTP / MFA
        - WhatsApp Integration
        - Token Management
        - Security Features
        - Rate Limiting / IP Banning
        - JWT Sessions
        - Email Configuration
        - Template Customization
        - Admin UI
        - API / Backend
        - Documentation
        - License System
        - Other
    validations:
      required: true
      
  - type: textarea
    id: problem
    attributes:
      label: Problem / Use Case
      description: What problem does this feature solve?
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like to see this implemented?
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternatives?
    validations:
      required: false
      
  - type: textarea
    id: example
    attributes:
      label: Example
      description: Provide examples, mockups, or code snippets
    validations:
      required: false
      
  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched for similar feature requests
          required: true
